// User actions
export const USER_LOGIN = 'USER_LOGIN';
export const USERNAME = 'USERNAME';
export const REGISTRATION_FAILED_MESSAGE = 'REGISTRATION_FAILED_MESSAGE';
export const LOGIN_FAILED_MESSAGE = 'LOGIN_FAILED_MESSAGE';
export const SHOW_USER_OR_REG_LOGIN_MODAL = 'SHOW_USER_OR_REG_LOGIN_MODAL';

// Tweet actions
export const TWEET_ARRAY = 'TWEET_ARRAY';